# A conda environment with all useful package for ctapipe developers
name: magic-lst
channels:
  - conda-forge
  - default
dependencies:
  - python=3.8
  - numpy>=1.17
  - astropy>=4.0.5,<5
  - pip
  - corsikaio
  - ctapipe~=0.12
  - eventio>=1.5.1,<2.0.0a0
  - gammapy=0.18.2
  - h5py
  - ipython
  - jupyter
  - matplotlib>=3.5
  - notebook
  - numba
  - joblib
  - pyparsing
  - pytables
  - pytest
  - pytest-cov
  - pytest-runner
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - sphinx~=4.2
  - sphinx-automodapi
  - sphinx_rtd_theme
  - sphinx-argparse
  - vitables
  - nbsphinx
  - numpydoc
  - tqdm
  - toml
  - traitlets~=5.0.5
  - pandas
  - pip:
      - ctapipe_io_magic~=0.4.0
      - uproot~=4.1
      - ctaplot~=0.5.3
      - pyirf~=0.5.0
