# MAGIC-LST configuration file example

# --- DATA FILES ---------------------------------------------------------------
data_files:
  mc:
    train_sample:
      mask_sim: '/mnt/d/CTA-MC/DL0/*.simtel.gz'
      hillas_h5: '/mnt/d/CTA-MC/DL0/Hillas_Stereo.h5'
      reco_h5: '/mnt/d/CTA-MC/DL0/Reco.h5' 
    test_sample:
      mask_sim: '/mnt/d/CTA-MC/DL0/*.simtel.gz'
      hillas_h5: '/mnt/d/CTA-MC/DL0/Hillas_Stereo.h5'
      reco_h5: '/mnt/d/CTA-MC/DL0/Reco.h5' 

  data:
    train_sample:
      mask_sim: '/mnt/d/CTA-MC/DL0/*.simtel.gz'
      hillas_h5: '/mnt/d/CTA-MC/DL0/Hillas_Stereo.h5'
      reco_h5: '/mnt/d/CTA-MC/DL0/Reco.h5' 
    test_sample:
      mask_sim: '/mnt/d/CTA-MC/DL0/*.simtel.gz'
      hillas_h5: '/mnt/d/CTA-MC/DL0/Hillas_Stereo.h5'
      reco_h5: '/mnt/d/CTA-MC/DL0/Reco.h5' 

# --- TELESCOPES ---------------------------------------------------------------
all_tels:
  tel_ids: [1, 2, 3, 4, 5, 6]
  tel_n: ['LST', 'MAGIC']
  tel_n_short: ['LST', 'M']

LST:
  tel_ids: [1, 2, 3, 4]
  cleaning_config:
    boundary_thresh: 4
    keep_isolated_pixels: true
    min_number_picture_neighbors: 0
    picture_thresh: 8
  camera_name: 'LSTCam'
  min_pixel: 5

MAGIC:
  tel_ids: [5, 6]
  cleaning_config:
    boundary_thresh: 3.5
    findhotpixels: false
    max_time_diff: 2.46
    max_time_off: 7.38
    picture_thresh: 6
    usesum: true
    usetime: true
  bad_pixel_config:
    pedestalLevel: 400
    destalLevelVariance: 4.5
    pedestalType: 'FromExtractorRndm'
  camera_name: 'MAGICCam'
  min_pixel: 5
  position: # MAGIC telescope positions in m wrt. to the center of CTA simulations
    5: [-27.24, -146.66, 50.0]
    6: [-96.44, -96.77, 51.0]
  
# --- GLOBAL -------------------------------------------------------------------
global:
  wrong_alt: 'tel_alt < 1.5707963267948966'


# --- TRAIN CLASSIFIER RF ------------------------------------------------------
classifier_rf:
  save_dir: '/mnt/d/CTA-MC/DL0/RFs/'
  joblib_name: 'classifier_rf.joblib'
  cuts: '(event_id > 0) & (multiplicity > 1) & (intensity > 30) & (length > 0.0) & (intensity_width_1 < 0.15)'
  wrong_alt: 'tel_alt < 1.5707963267948966'
  settings:
    n_estimators: 100
    min_samples_leaf: 10
    n_jobs: 3
  features: ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi', 'num_islands']
  fig_name: 'classifier_rf_gammaness'
  fig_size: [20, 10]

# --- TRAIN DIRECTION RF -------------------------------------------------------
direction_rf:
  save_dir: '/mnt/d/CTA-MC/DL0/RFs/'
  joblib_name: 'direction_rf.joblib'
  cuts: '(event_id > 0) & (multiplicity > 1) & (intensity > 30) & (length > 0.0) & (intensity_width_1 < 0.15)'
  settings:
    n_estimators: 100
    min_samples_leaf: 10
    n_jobs: 3
  features:
    'disp': ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi']
    'pos_angle_shift': ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi']
  fig_name_theta2: 'Direction_RF_theta2'
  fig_name_PSF_energy: 'Direction_RF_PSF_energy'
  fig_name_PSF_offset: 'Direction_RF_PSF_offset'
  fig_size: [12, 12]

# --- TRAIN ENERGY RF ----------------------------------------------------------
energy_rf:
  save_dir: '/mnt/d/CTA-MC/DL0/RFs/'
  joblib_name: 'energy_rf.joblib'
  cuts: '(event_id > 0) & (multiplicity > 1) & (intensity > 30) & (length > 0.0) & (intensity_width_1 < 0.15)'
  settings:
    n_estimators: 100
    min_samples_leaf: 10
    n_jobs: 3
  features: ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi', 'intensity_width_1', 'intensity_width_2']
  fig_name: 'Energy_RF_migmatrix'
  fig_size: [30, 10]
