data_files:
  mc:
    train_sample:
      mask_sim: "/mnt/d/CTA-MC/DL0/*.simtel.gz"
      # hillas_h5: "/mnt/d/CTA-MC/DL0/Hillas_Stereo.h5"
      hillas_h5: "/mnt/d/CTA-MC/MAGIC/MC_test_hillas.h5"
    test_sample:
      mask_sim: "/mnt/d/CTA-MC/DL0/*.simtel.gz"
      # hillas_h5: "/mnt/d/CTA-MC/DL0/Hillas_Stereo.h5"
      hillas_h5: "/mnt/d/CTA-MC/MAGIC/MC_test_hillas.h5"

  data:
    train_sample:
      mask_sim: "/mnt/d/CTA-MC/DL0/*.simtel.gz"
      # hillas_h5: "/mnt/d/CTA-MC/DL0/Hillas_Stereo.h5"
      hillas_h5: "/mnt/d/CTA-MC/MAGIC/MC_test_hillas.h5"
    test_sample:
      mask_sim: "/mnt/d/CTA-MC/DL0/*.simtel.gz"
      # hillas_h5: "/mnt/d/CTA-MC/DL0/Hillas_Stereo.h5"
      hillas_h5: "/mnt/d/CTA-MC/MAGIC/MC_test_hillas.h5"

telescopes: [1, 2, 3, 4, 5, 6]


LST:
  tel_ids: [1, 2, 3, 4]
  cleaning_config:
    boundary_thresh: 4
    keep_isolated_pixels: true
    min_number_picture_neighbors: 0
    picture_thresh: 8
  camera_name: "LSTCam"
  min_pixel: 5

MAGIC:
  tel_ids: [5, 6]
  cleaning_config:
    boundary_thresh: 3.5
    findhotpixels: false
    max_time_diff: 2.46
    max_time_off: 7.38
    picture_thresh: 6
    usesum: true
    usetime: true
  bad_pixel_config:
    pedestalLevel: 400
    destalLevelVariance: 4.5
    pedestalType: "FromExtractorRndm"
  camera_name: "MAGICCam"
  min_pixel: 5


classifier_rf:
    save_name: "/mnt/d/CTA-MC/DL0/RFs/classifier_rf.joblib"
    cuts: "(event_id > 0) & (multiplicity > 1) & (intensity > 30) & (length > 0.0) & (intensity_width_1 < 0.15)"
    settings:
        n_estimators: 100
        min_samples_leaf: 10
        n_jobs: 3
    
    features:
        ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi', 'n_islands']