file:
    input_mask: "/mnt/d/CTA-MC/DL0/*.simtel.gz"
    low_index: 3
    high_index: 6

telescopes: [1, 2, 3, 4, 5, 6]

LST:
    tel_ids: [1, 2, 3, 4]
    cleaning_config:
        boundary_thresh: 4
        keep_isolated_pixels: true
        min_number_picture_neighbors: 0
        picture_thresh: 8
    camera_name: "LSTCam"
    min_pixel: 5

MAGIC:
    tel_ids: [5, 6]
    cleaning_config:
        boundary_thresh: 3.5
        findhotpixels: false
        max_time_diff: 2.46
        max_time_off: 7.38
        picture_thresh: 6
        usesum: true
        usetime: true
    bad_pixel_config:
        pedestalLevel: 400
        destalLevelVariance: 4.5
        pedestalType: "FromExtractorRndm"
    camera_name: "MAGICCam"
    min_pixel: 5
