data_files:
    mc:
        train_sample:
            magic:
                input_mask: "/remote/magicdata5/heckmann/Crab_CTA/ctapipe/MC_ST.03.12/Train_sample/1.Calibrated/GA_*root"
                hillas_output: "/remote/magicdata5/ejobst/Crab_CTA/MC/Train/Hillas/hillas_stereo_MAGICCleaning_v20211006.h5"
                       
        test_sample:
            magic:
                input_mask: "/remote/magicdata5/heckmann/Crab_CTA/ctapipe/MC_ST.03.12/Test_sample/1.Calibrated/GA_*root"
                hillas_output: "/remote/magicdata5/ejobst/Crab_CTA/MC/Test/Hillas/hillas_stereo_MAGICCleaning_v20211006.h5"
                reco_output: "/remote/magicdata5/ejobst/Crab_CTA/MC/Test/Reco/reco_stereo_MAGICCleaning_v20211006.h5"
 
    data:
       test_sample:
           magic:
               input_mask: "/remote/magicdata5/heckmann/Crab_CTA/ctapipe/Crab/2019_11_27/1.Calibrated/data/20191127*.root"
               hillas_output: "/remote/magicdata5/ejobst/Crab_CTA/Data/Test/19_11_27/Hillas/hillas_stereo_MAGICCleaning_v20211006.h5"
               reco_output: "/remote/magicdata5/ejobst/Crab_CTA/Data/Test/19_11_27/Reco/reco_stereo_MAGICCleaning_v20211006.h5"

       train_sample:
           magic:
               input_mask: "/remote/magicdata5/heckmann/Crab_CTA/ctapipe/Off/1.Calibrated/20*root"
               hillas_output: "/remote/magicdata5/ejobst/Crab_CTA/Data/Train/Hillas/hillas_stereo_MAGICCleaning_v20211006.h5"

image_cleaning:
    magic:
        picture_thresh: 6
        boundary_thresh: 3.5
        min_number_picture_neighbors: 1
        # 1.5 slices x 1.64 GHz
        max_time_diff: 2.46
        # 4.5 slices x 1.64 GHz
        max_time_off: 7.38
        min_number_neighbors: 3
        usetime : True
        usesum : True
        findhotpixels : True

bad_pixels:
    magic:
        pedestalLevel: 400
        pedestalLevelVariance: 4.5
        pedestalType: "FromExtractorRndm"
        
energy_rf:
    save_name: "/remote/magicdata5/ejobst/Crab_CTA/RFs/energy_rf_MAGICCleaning_v20211006.joblib"
    cuts: "(event_id > 0) & (multiplicity > 1) & (intensity > 30) & (length > 0.0) & (intensity_width_1 < 0.15)"
    settings:
        n_estimators: 100
        min_samples_leaf: 10
        n_jobs: 3
    
    features:
        ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi', 'intensity_width_1', 'intensity_width_2', 'h_max', 'alt', 'az']

direction_rf:
    save_name: "/remote/magicdata5/ejobst/Crab_CTA/RFs/direction_rf_MAGICCleaning_v20211006.joblib"
    cuts: "(event_id > 0) & (multiplicity > 1) & (intensity > 30) & (length > 0.0) & (intensity_width_1 < 0.15)"
    settings:
        n_estimators: 100
        min_samples_leaf: 10
        n_jobs: 3
    
    features:
        'disp': ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi', 'h_max', 'alt', 'az']
        'pos_angle_shift': ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi', 'h_max', 'alt', 'az']


classifier_rf:
    save_name: "/remote/magicdata5/ejobst/Crab_CTA/RFs/classifier_rf_MAGICCleaning_v20211006.joblib"
    cuts: "(event_id > 0) & (multiplicity > 1) & (intensity > 30) & (length > 0.0) & (intensity_width_1 < 0.15)"
    settings:
        n_estimators: 100
        min_samples_leaf: 10
        n_jobs: 3
    
    features:
        ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi', 'n_islands', 'h_max', 'alt', 'az']
        
        
irf:
    output_name: "/remote/magicdata5/ejobst/Crab_CTA/IRF_file/outfile_MAGICCleaning_v20211006.fits"

source:
    name: "Crab"
    coordinates:
        ra_dec: [83.633083, 22.0145]

event_list:
    output_directory: "/remote/magicdata5/ejobst/Crab_CTA/events_MAGICCleaning_v20211006"
    max_time_diff: 6.9e-4
    cuts:
        quality:
            l3rate: "80 < value < 1000"
            dc: "0 < value < 7e3"
        selection:
            "(event_id > 0) & (multiplicity > 1) & (abs(pos_angle_shift_reco - 0.5) > 0.4) & (event_class_0 > 0.8)"

spectrum:
    input_files: "/remote/magicdata5/ejobst/Crab_CTA/events_MAGICCleaning_v20211006/events*.fits"
    energy_reco_nbins: 30
    energy_reco_min: 0.005  # TeV
    energy_reco_max: 50.    # TeV
    energy_true_factor: 1.4      # ratio of number of estimated-to-true energy bins
    off_positions: 3
    #exclude_region: {0 : [183.604, -8.708, 0.5]}
    spectral_model:
        power_law: {'index' : 2, 'amplitude' : 2.0e-11, 'reference' : 0.3}
        #log_parabola: {'alpha' : 2, 'amplitude' : 2.0e-11, 'beta' : 0.2, 'reference' : 0.3}
