  # Configuration file to be used for stereo analysis of MAGIC data.
# In the several input_mask keys, one has to include files from
# both M1 and M2, since the MAGICEventSource will match the events
# to get the stereo events.

data_files:
    mc:
      train_sample:
        magic:
          input_mask: "/home/gpirola/Desktop/MC_ST0307/MC_medium/Calibrated/seed171950/test_2/GA_M*.root"
          hillas_output: "/home/gpirola/Desktop/MC_ST0307/MC_medium/DL1/train/GA_za35to50_DL1_train_Melibea_175_2.h5"
      test_sample:
        magic:
          input_mask: "/home/gpirola/Desktop/MC_ST0307/MC_medium/Calibrated/seed184951/GA_M*.root"
          hillas_output: "/home/gpirola/Desktop/MC_ST0307/MC_medium/DL1/test/GA_za35to50_DL1_test_Melibea_174_2.h5"
          reco_output: "/home/gpirola/Desktop/MC_ST0307/MC_medium/DL1/test_reco/GA_za35to50_DL1_test_Melibea_174_2_reco_SingleRF_prova.h5"
    data:
      train_sample:
        magic:
          input_mask: "/path/to/data_train_files/20*_Y_*.root"
          hillas_output: "/home/gpirola/Desktop/MC_ST0307/MC_medium/DL1/train/other/GA_za35to50_DL1_train_impact_proton.h5"
      test_sample:
        magic:
          input_mask: "/path/to/data_test_files/20*_Y_*.root"
          hillas_output: "/home/gpirola/Desktop/MC_ST0307/MC_medium/DL1/test/GA_za35to50_DL1_test_impact_proton.h5"
          reco_output: "/home/gpirola/Desktop/MC_ST0307/MC_medium/DL1/GA_za35to50_DL1_test_impact_proton_reco.h5"

image_cleaning:
    magic:
        charge_thresholds:
            picture_thresh: 6
            boundary_thresh: 3.5
            min_number_picture_neighbors: 1

        time_thresholds:
            # 1.5 slices x 1.64 GHz
            max_time_diff: 2.46
            # 4.5 slices x 1.64 GHz
            max_time_off: 7.38
            min_number_neighbors: 1

energy_rf:
    save_name: "/home/gpirola/Desktop/MC_ST0307/RFs/energy/energy_rf_medium=singleRF.joblib"
    cuts: "(event_id > 0) & (multiplicity > 1) & (stereo_rec_bool>0)"
    #cuts: "(event_id > 0) & (multiplicity > 1) & (intensity>50) & (length > 0.0) & (intensity_width_1 < 0.15)"
    #cuts: "(event_id > 0) & (multiplicity > 1) & (50<intensity<50000) & (length > 0.0) & (intensity_width_1 < 0.15) & (intensity_width_2 < 0.15) & (ch_radius>40) & (ch_density>0) "
    #cuts: "(event_id > 0) & (multiplicity > 1) & (intensity_1 > 50) & (intensity_2 > 50) & (length_1 > 0.0) & (length_2 > 0.0) & (intensity_width_1 < 0.15) & (intensity_width_2 < 0.15)"
    settings:
        n_estimators: 150
        min_samples_leaf: 5
        n_jobs: 4

    training_conditions:
        weight: False
        single_RF: True

    features:
        ['slope_1','slope_2', 'length_1','length_2', 'width_1', 'width_2' ,'log_intensity_1','log_intensity_2', 'intensity_width_1_1','intensity_width_1_2', 'intensity_width_2_1', 'intensity_width_2_2', 'h_max', 'alt','ch_density','ch_radius','CosBSangle','disp_reco_1','disp_reco_2','disp_Impact_1','disp_Impact_2']
        #['ch_density', 'log_intensity','slope','ch_radius', 'width', 'length', 'intensity_width_1', 'intensity_width_2', 'h_max', 'alt','CosBSangle','disp_reco','disp_Impact']
        #['slope', 'length', 'width', 'log_intensity','skewness', 'kurtosis' ,'intensity_width_1', 'intensity_width_2', 'h_max', 'alt','disp_reco']
        #['slope', 'length', 'width', 'log_intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi', 'intensity_width_1', 'intensity_width_2', 'h_max', 'alt', 'az']#,'disp_reco']
        #['slope', 'length', 'width','intensity', 'x', 'y', 'psi', 'intensity_width_1', 'intensity_width_2', 'h_max', 'alt', 'az','ch_density','ch_radius','CosBSangle']
        #['slope', 'length', 'width','intensity', 'x', 'y', 'psi', 'intensity_width_1', 'intensity_width_2', 'h_max', 'alt', 'az']#,'impact_1','impact_2']
        #['slope', 'length', 'width', 'x', 'y', 'psi', 'intensity_width_1', 'intensity_width_2', 'h_max', 'alt', 'az']#,'impact_1','impact_2']
        #['slope', 'length', 'width', 'log_intensity', 'intensity_width_1', 'intensity_width_2', 'h_max', 'alt','impact_1','impact_2']

direction_rf:
    save_name: "/home/gpirola/Desktop/MC_ST0307/RFs/direction/direction_rf_medium.joblib"
    cuts: "(event_id > 0) & (multiplicity > 1) & (intensity > 50) & (length > 0.0) & (intensity_width_1 < 0.15)"
    settings:
        n_estimators: 100
        min_samples_leaf: 10
        n_jobs: 3
    training_conditions:
        weight: False
    features:
        'disp':       ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis','x', 'y', 'psi', 'h_max', 'alt', 'az']  # ['slope', 'length', 'width', 'intensity', 'x', 'y', 'psi', 'h_max', 'alt', 'az'] #['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi', 'h_max', 'alt', 'az']
        'pos_angle_shift': ['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi', 'h_max', 'alt', 'az'] #['slope', 'length', 'width', 'intensity', 'x', 'y', 'psi', 'h_max', 'alt', 'az'] #['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi', 'h_max', 'alt', 'az']

classifier_rf:
    save_name: "/home/gpirola/Desktop/MC_ST0307/RFs/classifier/classifier_rf_medium_prova.joblib"
    cuts: "(event_id > 0) & (multiplicity > 1) & (intensity > 50) & (length > 0.0) & (intensity_width_1 < 0.15)"
    settings:
        n_estimators: 100
        min_samples_leaf: 10
        n_jobs: 3
    training_conditions:
        weight: False
    features:
        #['slope', 'length', 'width', 'intensity', 'skewness', 'kurtosis', 'x', 'y', 'psi', 'n_islands', 'h_max', 'alt', 'az']
        ['slope', 'length', 'width', 'intensity', 'x', 'y', 'psi', 'n_islands', 'h_max', 'alt', 'az']

irf:
    output_name: "/path/to/IRF_file/outfile.fits"

source:
    name: "Crab"
    coordinates:
        ra_dec: [83.633083, 22.0145]

event_list:
    max_time_diff: 6.9e-4
    cuts:
        quality:
            l3rate: "80 < value < 1000"
            dc: "0 < value < 7e3"
        selection:
            "(event_id > 0) & (multiplicity > 1) & (event_class_0 > 0.8)"
