Data:
  dates: ["2020_12_14","2020_12_16"] #dates
  run-numbers: ["05093664", "05093663", "05093711"] #runnumbers, does not have to be sorted
  input-path: "/remote/ceph/group/magic/MAGIC-LST/Data/MAGIC/CrabNebula/1.Calibrated/"
  output-path: "/home/iwsatlas1/ejobst/Software/Internship/Elli/temp_folder_2"

MCs:
  input-path: "/home/iwsatlas1/ejobst/Software/Internship/Elli/mcp/magic/simtel"

Settings:
  RFs: ["energy", "classifier", "direction"]


