mc_tel_ids:
    LST-1: 1
    MAGIC-I: 2
    MAGIC-II: 3


LST:
    image_extractor:
        type: 'LocalPeakWindowSum'
        window_shift: 4
        window_width: 8

    increase_nsb:
        use: true
        extra_noise_in_dim_pixels: 1.2
        extra_bias_in_dim_pixels: 0.5
        transition_charge: 8
        extra_noise_in_bright_pixels: 1.2

    increase_psf:
        use: true
        smeared_light_fraction: 0.125

    tailcuts_clean:
        picture_thresh: 8
        boundary_thresh: 4
        keep_isolated_pixels: false
        min_number_picture_neighbors: 2

    time_delta_cleaning:
        use: true
        min_number_neighbors: 1
        time_limit: 2

    dynamic_cleaning:
        use: true
        threshold: 267
        fraction: 0.03

    use_only_main_island: false


MAGIC:
    image_extractor:
        type: 'SlidingWindowMaxSum'
        window_width: 5
        apply_integration_correction: false

    charge_correction:
        use: true
        correction_factor: 1.143

    magic_clean:
        use_time: true
        use_sum: true
        picture_thresh: 6
        boundary_thresh: 3.5
        max_time_off: 4.5
        max_time_diff: 1.5
        find_hotpixels: 'auto'
        pedestal_type: 'from_extractor_rndm'   # select 'fundamental', 'from_extractor' or 'from_extractor_rndm'

    muon_ring:
        thr_low: 25
        tailcut: [12, 8]
        ring_completeness_threshold: 25


event_coincidence:
    type_lst_time: 'dragon_time'   # select 'dragon_time', 'tib_time' or 'ucts_time'
    window_width: 0.6   # unit: [usec]
    offset_start: -10.0   # unit: [usec]
    offset_stop: 0.0   # unit: [usec]


stereo_reco:
    quality_cuts: '(intensity > 50) & (width > 0)'
    theta_uplim: 6   # unit: [arcmin]


energy_regressor:
    settings:
        n_estimators: 150
        criterion: 'squared_error'
        max_depth: 50
        min_samples_split: 2
        min_samples_leaf: 2
        min_weight_fraction_leaf: 0.0
        max_features: 'auto'
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: 5
        random_state: 42
        verbose: 0
        warm_start: false
        ccp_alpha: 0.0
        max_samples: null

    features: [
        'intensity',
        'length',
        'width',
        'skewness',
        'kurtosis',
        'slope',
        'intensity_width_2',
        'h_max',
        'impact',
    ]


direction_regressor:
    settings:
        n_estimators: 150
        criterion: 'squared_error'
        max_depth: 50
        min_samples_split: 2
        min_samples_leaf: 2
        min_weight_fraction_leaf: 0.0
        max_features: 'auto'
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: 5
        random_state: 42
        verbose: 0
        warm_start: false
        ccp_alpha: 0.0
        max_samples: null

    features: [
        'intensity',
        'length',
        'width',
        'skewness',
        'kurtosis',
        'slope',
        'intensity_width_2',
        'h_max',
        'impact',
    ]


event_classifier:
    settings:
        n_estimators: 100
        criterion: 'gini'
        max_depth: 100
        min_samples_split: 2
        min_samples_leaf: 2
        min_weight_fraction_leaf: 0.0
        max_features: 'auto'
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: 5
        random_state: 42
        verbose: 0.0
        warm_start: false
        class_weight: null
        ccp_alpha: 0.0
        max_samples: null

    features: [
        'intensity',
        'length',
        'width',
        'skewness',
        'kurtosis',
        'slope',
        'intensity_width_2',
        'h_max',
        'impact',
    ]


create_irf:
    quality_cuts: null
    irf_type: 'software'   # select 'hardware', 'software', 'software_with_any2' or 'magic_stereo'
    dl2_weight: null   # type of the weight for averaging tel-wise DL2 parameters, null, 'uncert' or 'intensity'

    energy_bins:
        start: 0.01   # unit: [TeV]
        stop: 100   # unit: [TeV]
        n_bins: 20   # number of bins in log space

    migration_bins:
        start: 0.2
        stop: 5
        n_bins: 30   # number of bins in geom space

    bkg_fov_offset_bins:
        start: 0   # unit: [deg]
        stop: 10   # unit: [deg]
        n_bins: 20   # number of bins in linear space

    gammaness:
        cut_type: 'dynamic'   # select 'global' or 'dynamic'
        global_cut_value: 0.8   # used for the global cut
        gamma_efficiency: 0.9   # used for the dynamic cut
        min_cut: 0.05   # used for the dynamic cut
        max_cut: 0.85   # used for the dynamic cut

    theta:
        cut_type: 'global'   # select 'global' or 'dynamic'
        global_cut_value: 0.2   # used for the global cut
        gamma_efficiency: 0.75   # used for the dynamic cut
        min_cut: 0.1   # used for the dynamic cut
        max_cut: 0.45   # used for the dynamic cut


dl2_to_dl3:
    source_name: 'Crab'
    source_ra: null   # used when the source name is null
    source_dec: null   # used when the source name is null
