mc_tel_ids:
    LST-1: 1
    MAGIC-I: 2
    MAGIC-II: 3


LST:
    image_extractor:
        type: "LocalPeakWindowSum"
        window_shift: 4
        window_width: 8

    increase_nsb:
        use: true
        extra_noise_in_dim_pixels: 1.2
        extra_bias_in_dim_pixels: 0.5
        transition_charge: 8
        extra_noise_in_bright_pixels: 1.2

    increase_psf:
        use: true
        smeared_light_fraction: 0.125

    tailcuts_clean:
        picture_thresh: 8
        boundary_thresh: 4
        keep_isolated_pixels: false
        min_number_picture_neighbors: 2

    time_delta_cleaning:
        use: true
        min_number_neighbors: 1
        time_limit: 2

    dynamic_cleaning:
        use: true
        threshold: 267
        fraction: 0.03

    use_only_main_island: false


MAGIC:
    image_extractor:
        type: "SlidingWindowMaxSum"
        window_width: 5
        apply_integration_correction: false

    charge_correction:
        use: true
        correction_factor: 1.143

    magic_clean:
        use_time: true
        use_sum: true
        picture_thresh: 6
        boundary_thresh: 3.5
        max_time_off: 4.5
        max_time_diff: 1.5
        find_hotpixels: true
        pedestal_type: "from_extractor_rndm"

    muon_ring:
        thr_low: 25
        tailcut: [12, 8]
        ring_completeness_threshold: 25


event_coincidence:
    timestamp_type_lst: "dragon_time"  # select "dragon_time", "tib_time" or "ucts_time"
    window_width: 0.6  # unit: [usec]
    time_offset:
        start: -10.0  # unit: [usec]
        stop: 0.0  # unit: [usec]


stereo_reco:
    quality_cuts: "(intensity > 50) & (width > 0)"
    theta_uplim: 6  # unit: [arcmin]


energy_regressor:
    settings:
        n_estimators: 150
        criterion: "squared_error"
        max_depth: 50
        min_samples_split: 2
        min_samples_leaf: 2
        min_weight_fraction_leaf: 0.0
        max_features: "auto"
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: 5
        random_state: 42
        verbose: 0
        warm_start: false
        ccp_alpha: 0.0
        max_samples: null

    features: [
        "intensity",
        "length",
        "width",
        "skewness",
        "kurtosis",
        "slope",
        "intensity_width_2",
        "h_max",
        "impact",
    ]

    gamma_offaxis:
        min: null  # unit: [deg]
        max: null  # unit: [deg]


direction_regressor:
    settings:
        n_estimators: 150
        criterion: "squared_error"
        max_depth: 50
        min_samples_split: 2
        min_samples_leaf: 2
        min_weight_fraction_leaf: 0.0
        max_features: "auto"
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: 5
        random_state: 42
        verbose: 0
        warm_start: false
        ccp_alpha: 0.0
        max_samples: null

    features: [
        "intensity",
        "length",
        "width",
        "skewness",
        "kurtosis",
        "slope",
        "intensity_width_2",
        "h_max",
        "impact",
    ]

    gamma_offaxis:
        min: null  # unit: [deg]
        max: null  # unit: [deg]


event_classifier:
    settings:
        n_estimators: 100
        criterion: "gini"
        max_depth: 100
        min_samples_split: 2
        min_samples_leaf: 2
        min_weight_fraction_leaf: 0.0
        max_features: "auto"
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: 5
        random_state: 42
        verbose: 0.0
        warm_start: false
        class_weight: null
        ccp_alpha: 0.0
        max_samples: null

    features: [
        "intensity",
        "length",
        "width",
        "skewness",
        "kurtosis",
        "slope",
        "intensity_width_2",
        "h_max",
        "impact",
    ]

    gamma_offaxis:
        min: null  # unit: [deg]
        max: null  # unit: [deg]


create_irf:
    quality_cuts: null
    irf_type: "software"  # select "hardware", "software(_with_any2)" or "magic_stereo"
    dl2_weight: null  # select null, "variance" or "intensity"
    obs_time: 50  # used for modeling backgrounds, unit: [hour]

    energy_bins:   # log space
        start: 0.01   # unit: [TeV]
        stop: 1000   # unit: [TeV]
        num: 26   # number of edges (nbins = num - 1)

    migration_bins:  # log space
        start: 0.2
        stop: 5
        num: 31  # number of edges (nbins = num - 1)

    fov_offset_bins:  # linear space
        start: 0.3  # unit: [deg]
        stop: 0.5  # unit: [deg]
        num: 2  # number of edges (nbins = num - 1)

    bkg_fov_offset_bins:  # linear space
        start: 0  # unit: [deg]
        stop: 10  # unit: [deg]
        num: 21  # number of edges (nbins = num - 1)

    gammaness:
        cut_type: "dynamic"   # select "global" or "dynamic"
        global_cut_value: 0.8   # used for the global cut
        efficiency: 0.9   # used for the dynamic cut
        min_cut: 0.05   # used for the dynamic cut
        max_cut: 0.85   # used for the dynamic cut

    theta:
        cut_type: "global"   # select "global" or "dynamic"
        global_cut_value: 0.2   # used for the global cut
        efficiency: 0.75   # used for the dynamic cut
        min_cut: 0.1   # used for the dynamic cut
        max_cut: 0.45   # used for the dynamic cut


dl2_to_dl3:
    irf_interpolation_method: "nearest" # "nearest" - no interpolation (closest point taken), "linear", "cubic" - interpolation
    source_name: "Crab"
    source_ra: null   # used when the source name is null
    source_dec: null   # used when the source name is null

